Repository wecode-bootcamp-korea/13-FORKFOLK-frontend, pull requests merged in 2020-10, with the labels that each got.

#2 [13기 구현정] Add : footer 구현 및 기본 CSS 구현
  .eslintrc.json
  public/images/forkfolk.jpg
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
Labels: Status: 리뷰 요청

#7 [13기 구현정] common.scss 추가사항 설정
  src/styles/common.scss
Labels: Status: Accepted

#4 [13기 이예린] AccountPage
  src/Routes.js
  src/pages/Account/Account.js
  src/pages/Account/Account.scss
  src/pages/Account/AccountForm/AccountForm.js
  src/pages/Account/AccountForm/AccountForm.scss
Labels: Status: 리뷰 요청

#3 [13기 구현정] Fix : Conflict 해결
  package-lock.json
  package.json
  public/index.html
  src/Routes.js
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/new folk.png
  src/components/SideMenu/SideMenu.js
  src/components/SideMenu/SideMenu.scss
  src/pages/Account/Account.js
  src/pages/Account/Account.scss
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#5 [13기 이예린] Add : ProductDetail Page 리뷰요청
  public/Data/ProductDetailData.json
  src/Routes.js
  src/config.js
  src/pages/Account/Account.js
  src/pages/ProductDetail/ProductCartMenu/ProductCartMenu.js
  src/pages/ProductDetail/ProductCartMenu/ProductCartMenu.scss
  src/pages/ProductDetail/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/ProductDescription/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.js
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.scss
  src/pages/ProductDetail/ProductThumbnail/cursorLeft.cur
  src/pages/ProductDetail/ProductThumbnail/cursorRight.cur
Labels: Status: 리뷰 요청

#1 [13기 백은진] Add : 상품 리스트 화면 구현
  package-lock.json
  package.json
  public/Data/a.html
  public/Data/cartList.json
  public/Data/productFilterList.json
  public/Data/productList.json
  src/Routes.js
  src/config.js
  src/index.js
  src/pages/Account/Account.js
  src/pages/CartList/CartList.js
  src/pages/CartList/CartList.scss
  src/pages/ProductList/Components/Product.js
  src/pages/ProductList/Components/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: Status: Accepted

#9 [13기 이예린] ProductDetail 화면 mock 데이터로 변경(중간발표 위해서)
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.scss
Labels: Status: 리뷰 요청

#6 [13기 임향수] Modify: 동적 라우팅 형태로 수정
  package-lock.json
  package.json
  public/Data/Artsdata.json
  public/Data/CoreContentsdata.json
  public/Data/Designdata.json
  public/Data/Fashiondata.json
  public/Data/Interiordata.json
  react-pagination/.gitignore
  react-pagination/README.md
  react-pagination/package-lock.json
  react-pagination/package.json
  react-pagination/public/favicon.ico
  react-pagination/public/index.html
  react-pagination/public/logo192.png
  react-pagination/public/logo512.png
  react-pagination/public/manifest.json
  react-pagination/public/robots.txt
  react-pagination/src/App.css
  react-pagination/src/App.js
  react-pagination/src/App.test.js
  react-pagination/src/index.css
  react-pagination/src/index.js
  react-pagination/src/logo.svg
  react-pagination/src/reportWebVitals.js
  react-pagination/src/setupTests.js
  src/Routes.js
  src/components/CoreContents/CoreContents.js
  src/components/CoreContents/CoreContents.scss
  src/components/CoreContents/SubContents/SubContents.js
  src/components/CoreContents/SubContents/SubContents.scss
  src/config.js
  src/index.js
  src/pages/Stories/Stories.js
  src/pages/Stories/Stories.scss
Labels: Status: 리뷰 요청

#15 [13기 임향수] Modify: Conflict 해결 + refactoring
  src/components/CoreContents/CoreContents.js
  src/components/CoreContents/CoreContents.scss
  src/components/CoreContents/SubContents/SubContents.js
  src/components/CoreContents/SubContents/SubContents.scss
  src/config.js
  src/pages/Stories/Stories.js
  src/pages/Stories/Stories.scss
Labels: Status: 리뷰 요청

#16 [13기 임향수] Add: button hover effect 구현
  public/Data/Artsdata.json
  src/pages/Stories/Stories.js
  src/pages/Stories/Stories.scss
Labels: Status: 리뷰 요청

#14 [13기 이예린] Account 페이지 (Refactoring 완료)
  .eslintrc.json
  .prettierrc
  src/Routes.js
  src/config.js
  src/pages/Account/Account.js
  src/pages/Account/Account.scss
  src/pages/Account/AccountForm/AccountForm.js
  src/pages/Account/AccountForm/AccountForm.scss
  src/pages/CartList/CartList.js
  src/pages/ProductDetail/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 수정 요청

#8 [13기 백은진] Cart list 페이지 "Add: 장바구니 페이지 레이아웃, 기능 구현"
  .eslintrc.json
  .prettier.json
  package-lock.json
  package.json
  public/Data/cartList.json
  public/Data/productList.json
  src/Routes.js
  src/config.js
  src/pages/CartList/CartList.js
  src/pages/CartList/CartList.scss
  src/pages/CartList/Components/CartProduct.js
  src/pages/CartList/Components/CartProduct.scss
  src/pages/ProductList/Components/Product.js
  src/pages/ProductList/Components/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#12 [13기 백은진] Product list 페이지 : "Add : 카테고리 및 페이지 클릭 시, 백엔드로 query string 전송하는 로직"
  src/pages/CartList/CartList.js
  src/pages/ProductList/Components/Product.js
Labels: Status: 수정 요청, Status: 컨플릭트 해결 요청

#11 [13기 이예린] ContentDetail페이지(Refactoring)
  .eslintrc.json
  public/Data/ContentDetailData.json
  src/Routes.js
  src/config.js
  src/pages/ContentDetail/ContentDetail.js
  src/pages/ContentDetail/ContentDetail.scss
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.js
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.scss
  src/pages/Stories/Stories.js
Labels: Status: Accepted

#10 [13기 이예린] ProductDetail 페이지 fetch경로 수정 (Refactoring)
  public/Data/ProductDetailData.json
  react-pagination/.gitignore
  react-pagination/README.md
  react-pagination/package-lock.json
  react-pagination/package.json
  react-pagination/public/favicon.ico
  react-pagination/public/index.html
  react-pagination/public/logo192.png
  react-pagination/public/logo512.png
  react-pagination/public/manifest.json
  react-pagination/public/robots.txt
  react-pagination/src/App.css
  react-pagination/src/App.js
  react-pagination/src/App.test.js
  react-pagination/src/index.css
  react-pagination/src/index.js
  react-pagination/src/logo.svg
  react-pagination/src/reportWebVitals.js
  react-pagination/src/setupTests.js
  src/config.js
  src/pages/CartList/CartList.js
  src/pages/ContentDetail/ContentDetail.js
  src/pages/ProductDetail/ProductCartMenu/ProductCartMenu.js
  src/pages/ProductDetail/ProductCartMenu/ProductCartMenu.scss
  src/pages/ProductDetail/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/ProductDescription/ProductDescription.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.js
  src/pages/ProductDetail/ProductThumbnail/ProductTumbnail.scss
  test.html
Labels: Status: 수정 요청

#18 [13기 백은진] ProductList & CartList : API 연결하여 맞춘 후, refactoring 완료
  src/Routes.js
  src/pages/CartList/CartList.js
  src/pages/CartList/Components/CartProduct.js
  src/pages/ContentDetail/ContentDetail.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/Components/Product.js
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#17 [13기 구현정] FIC : 컨플릭트 해결
  public/Data/OrderData.json
  src/Routes.js
  src/components/Header/Header.js
  src/components/SideMenu/SideMenu.js
  src/config.js
  src/pages/Account/AccountForm/AccountForm.js
  src/pages/CartList/CartList.js
  src/pages/Checkout/Checkout.js
  src/pages/Checkout/Checkout.scss
  src/pages/Checkout/CheckoutFormInfo.js
  src/pages/Checkout/Images/american_logo.png
  src/pages/Checkout/Images/diners_logo.png
  src/pages/Checkout/Images/discover_logo.png
  src/pages/Checkout/Images/jcb_logo.png
  src/pages/Checkout/Images/master_logo.png
  src/pages/Checkout/Images/paypal_logo.png
  src/pages/Checkout/Images/visa_logo.png
  src/pages/Checkout/components/Order.js
  src/pages/Checkout/components/Order.scss
  src/pages/Checkout/components/OrderInfoInput.js
  src/pages/Checkout/components/OrderInfoInput.scss
  src/pages/Checkout/components/OrderItem.js
  src/pages/Checkout/components/PaymentChoice.js
  src/pages/Checkout/components/PaymentChoice.scss
  src/pages/Main/components/FlexItemsList.scss
  src/pages/ProductList/Components/Product.js
  src/pages/Stories/Stories.scss
Labels: Status: 컨플릭트 해결 요청

#19 [13기 백은진] Feature/new product and cart list : 코드 리팩토링 완료
  src/pages/CartList/CartList.scss
  src/pages/CartList/Components/CartProduct.js
  src/pages/ProductList/Components/Product.js
  src/pages/ProductList/ProductList.js
Labels: Status: Accepted
